using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

public static class Extensions
{
    // ToTitleCase()
    public static string ToTitleCase(this string text)
    {
        return CultureInfo.CurrentCulture.TextInfo.ToTitleCase(text.ToLower());
    }

    // IsNullOrEmpty()
    public static bool IsNullOrEmpty<T>(this List<T> list)
    {
        return list == null || list.Count == 0;
    }

    // ToWords() 0-999
    public static string ToWords(this int number)
    {
        string[] ones =
        {
            "Zero","One","Two","Three","Four","Five","Six","Seven","Eight","Nine",
            "Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen",
            "Seventeen","Eighteen","Nineteen"
        };

        string[] tens =
        {
            "","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"
        };

        if (number < 20)
            return ones[number];

        if (number < 100)
            return tens[number / 10] + (number % 10 == 0 ? "" : " " + ones[number % 10]);

        return ones[number / 100] + " Hundred" +
               (number % 100 == 0 ? "" : " " + (number % 100).ToWords());
    }
}

class Employee
{
    public string Name { get; set; } = "";
    public double Salary { get; set; }
}

class Program
{
    static void Main()
    {
        Console.WriteLine("===== TASK 2.14 =====");

        string text = "bridge course week two";
        Console.WriteLine(text.ToTitleCase());

        List<int> numbers = new();
        Console.WriteLine($"List Empty : {numbers.IsNullOrEmpty()}");

        numbers.Add(10);
        Console.WriteLine($"List Empty : {numbers.IsNullOrEmpty()}");

        int value = 256;
        Console.WriteLine($"{value} -> {value.ToWords()}");

        Console.WriteLine("\nAnonymous Type");

        List<Employee> employees = new()
        {
            new(){Name="John",Salary=60000},
            new(){Name="Alice",Salary=50000},
            new(){Name="Bob",Salary=70000}
        };

        var result = employees.Select(e => new
        {
            e.Name,
            AnnualSalary = e.Salary * 12
        });

        foreach (var e in result)
            Console.WriteLine($"{e.Name} - {e.AnnualSalary}");

        Console.WriteLine("\nAnonymous types cannot be returned from methods");
        Console.WriteLine("because their type is generated by the compiler.");
    }
}